# print the 6 students mark and sort it
marks=[]
f1=int(input("enter the mark:"))
marks.append(f1)
f2=int(input("enter the mark:"))
marks.append(f2)
f3=int(input("enter the mark:"))
marks.append(f3)
f4=int(input("enter the mark:"))
marks.append(f4)
f5=int(input("enter the mark:")) 
marks.append(f5)
f6=int(input("enter the mark:"))
marks.append(f6)
print(marks)
marks.sort()
print(marks)
