s1 = set()
n = input("Enter a number:")
s1.add(int(n))
n = input("Enter a number:")
s1.add(int(n))
n = input("Enter a number:")
s1.add(int(n))
n = input("Enter a number:")
s1.add(int(n))
n = input("Enter a number:")
s1.add(int(n))
n = input("Enter a number:")
s1.add(int(n))
n = input("Enter a number:")
s1.add(int(n))
print(s1)