a = int(input("enter a number 1:"))
b = int(input("enter a number 2 :"))
print("the 1 number is",a)
print("the 2 number is",b)
print("square of number is",a**2)
print("average of number is",(a+b)/2)
print(type(a))
print(a+b)